MCU = STM32F401

BOOTLOADER = stm32-dfu

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

KEYBOARD_SHARED_EP = yes
CONSOLE_ENABLE = yes
MOUSE_SHARED_EP = yes

COMBO_ENABLE = yes

COMMAND_ENABLE = no